

  <div class="left-side">  
  <h1 class="title-page">Authentication Form</h1></br>
  <form method="POST" class="auth" action="?page=auth-form-action">

    <div class="field-form" >
      <input type="text" name="login" class="input-text"  placeholder="Login" required>
    </div> 

    <div class="field-form"> 
      <input type="password" name="password" class="input-text" placeholder="Password" required>
    </div> 

    <div class="field-form">
      <input type="submit" class="input-submit" value="Submit">
    </div>

    <div class="div-beyond-form">
      <a class="slyle-link-2" href="?page=registration">Registration User</a>
    </div>

  </form>
  </div>
