<div class="company-info">
	
	<div class="footer-menu-container footer-wrapper">
		<span class="company-color-text">GT-engineering</span>
		<ul class="footer-menu">
			<li><a href="?page=opc-hda">OPC-HDA</a></li>
			<li><a href="?page=systems">SYSTEMS</a></li>
			<li><a href="?page=product">PRODUCT</a></li>
			<li><a href="?page=contact">CONTACT</a></li>
			<li><a href="?page=re-count">Re-Count</a></li>
		</ul>
	</div>
	<div class="partners footer-wrapper">
		<span class="company-color-text">Development Partners</span>
		<div class="partners-links">
			<a href="http://www.matrikonopc.com/"><img src="/files/img/squiggle_icon_400x400.png" alt="" width="100px" height="100px"></a>
			<a href="https://opcfoundation.org/"><img src="/files/img/OPC_TR.png" alt="" width="200px" height="60px"></a>
		</div>
	</div>
	<div class="payment-system footer-wrapper">
		<span class="company-color-text">Payment System</span>
		<div class="partners-links">
			<img src="/files/img/PayPal-logo.png" alt="" width="200px" height="100px">
		</div>
	</div>

</div>

	<div class="footer-mail">
		<a href="mailto:support@automatic.co.ua" target="_top">support@automatic.co.ua</a>
	</div>