<head>
  <meta charset="UTF-8">
  <title><?php print $title; ?></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <meta name="description" content="<?php print $description; ?>">
  <link rel="shortcut icon" href="files/img/my-logo.png" type="image/png">
  <link rel="stylesheet" type="text/css" href="css/reset.css">
  <link rel="stylesheet" type="text/css" href="css/style.css">
  <link rel="stylesheet" type="text/css" href="css/responsive.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <script type="text/javascript" src="js/jquery-1.11.1.min.js"></script>
  <script type="text/javascript" src="js/script.js"></script>
  <script src='https://www.google.com/recaptcha/api.js'></script>
  <script type="text/javascript" src="files/libraries/onepage-scroll-master/jquery.onepage-scroll.js"></script>
  <link href='files/libraries/onepage-scroll-master/onepage-scroll.css' rel='stylesheet' type='text/css'>
    <!-- Magnific Popup core CSS file -->
  <link rel="stylesheet" href="files/libraries/magnific-popup/dist/magnific-popup.css"> 

  <!-- jQuery 1.7.2+ or Zepto.js 1.0+ -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> 

  <!-- Magnific Popup core JS file -->
  <script src="files/libraries/magnific-popup/dist/jquery.magnific-popup.js"></script>
</head>