
<div class="slider">
  <div class="item-slider" id="item-slider-1"><a href="?page=product"><img src="files/img/Baner-1.png" alt="" ></a></div>
  <div class="item-slider" id="item-slider-2"><a href="?page=systems"><img src="files/img/Baner-2.png" alt="" ></a></div>
  <div class="item-slider" id="item-slider-3"><a href="?page=systems"><img src="files/img/Baner-3.png" alt="" ></a></div>
</div>

<div class="section-main">
  <h1>Server application to collect technical data from SCADA via OPC HDA interface</h1>
</div>

<div class="section1"> 
  <div class="left-side">
    <iframe class="video" width="420" height="315" src="https://www.youtube.com/embed/Xdl2ZM95Ogw" frameborder="0" allowfullscreen></iframe>
  </div>


  <div class="right-side">
      <h1 class="company-info"><span class="company-color-text">GT-engineering</span></h1>   
      <p>
        <h2>Software company</h2>
       <span class="abz">We are company have more 5 year expirience</span> in OPC HDA technology. We are the company have more 5 year expirience in web development and technically development for industry solution. We help you in your ideas. We provide support for our software products 24 hours a day. We implement our software to our production individually.   
      </p>
  </div>
</div>

<div class="baner-4">
  <img id="b4" src="/files/img/baner-4.png" alt="">
</div>

<div class="company-wrapper">
   <div class="solution">
        <div class="item-solutions">
          <img src="files/img/icon-clock.png" alt="" class="icon-solution">
        </div>
        <div class="description">
          <p>
            <h1>Save Time</h1>
            Very good solution for those who need to get data on time. Our product allows you to read data from devices and SCADA systems automatically at a specified time.
          </p>
        </div>
        
    </div>

    <div class="solution">
        <div class="item-solutions">
          <img src="files/img/icon-report-about-read.png" alt="" class="icon-solution">
        </div>
        <div class="description">
          <p>
            <h1>Analyze Read data</h1>
            This Automatic OPC HDA client allows you to analyze the status of the read tag. He emeet detailed history of producing data for all tags.
          </p>
        </div>
    </div>

    <div class="solution">
        <div class="item-solutions">
          <img src="files/img/icon-report.png" alt="" class="icon-solution">
        </div>
        <div class="description">
          <p>
            <h1>Data in database</h1>
            As a result, you have a database with all the technical data from which will be obtained from your systems will be ready on time and to analyze them to your staff.
          </p>
        </div>
    </div>   
</div>