<div class="logo-wrapper">
	<a href="/" id="logo" ref="logo" title="GT-Engineering Software">
		<img src="../files/img/my-logo.png" class="logo" alt=="GT-Engineering Software">
	</a>
</div>
<div class="menu-wrapper">
	<div class="toogle">	
		<i class="fa fa-bars"></i>	
	</div>
	<ul class="menu">
		<li class="item-menu"><a href="?page=opc-hda" class="menu-link">opc hda</a></li>
		<li class="item-menu"><a href="?page=systems" class="menu-link">systems</a></li>	
		<li class="item-menu"><a href="?page=product" class="menu-link">product</a></li>
		<li class="item-menu"><a href="?page=blog" class="menu-link">blog</a></li>	
		<li class="item-menu"><a href="?page=contact" class="menu-link">contact us</a></li>
	</ul>
</div>	
